# Generated by Django 4.1.1 on 2022-10-11 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# blog.migrations.0003_auto_20221011_1931

class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_blogpost__author'), ('blog', '0003_auto_20221011_1931'), ('blog', '0004_remove_blogpost_author_alter_blogpost__author')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Blogpost Title')),
                ('author', models.CharField(max_length=40, verbose_name='Blogpost Author')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Blogpost Description')),
                ('pub_date', models.DateTimeField(verbose_name='Publication Date')),
                ('body', models.TextField(verbose_name='Blogpost body')),
                ('slug', models.SlugField(unique=True, verbose_name='Blogpost Slug')),
                ('_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            code=blog.migrations.0003_auto_20221011_1931.forwards,
            reverse_code=blog.migrations.0003_auto_20221011_1931.revert,
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='_author',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
